packages:
  - packages/*
  - apps/*

catalog:
  '@antfu/eslint-config': ^4.16.2
  '@types/node': ^22.15.21
  eslint: ^9.30.1
  tsx: ^4.17.0
  typescript: ^5.6.2
  vitest: ^3.0.5
  '@vitest/coverage-v8': ^3.0.2
  better-auth: 1.3.4
  unbuild: ^3.5.0
  tsdown: ^0.13.4

ignoredBuiltDependencies:
  - esbuild
  - tesseract.js

onlyBuiltDependencies:
  - canvas
  - core-js
  - sharp
