packages:
  - packages/*
  - apps/*

catalog:
  '@antfu/eslint-config': ^4.12.0
  '@types/node': ^22.5.4
  eslint: ^9.25.1
  tsx: ^4.17.0
  typescript: ^5.6.2
  vitest: ^3.0.5
  '@vitest/coverage-v8': ^3.0.2
  better-auth: ^1.2.4

ignoredBuiltDependencies:
  - esbuild
  - tesseract.js

onlyBuiltDependencies:
  - canvas
  - core-js
  - sharp
