packages:
  - packages/*
  - apps/*

catalog:
  '@antfu/eslint-config': ^6.1.0
  '@types/node': ^22.15.21
  eslint: ^9.38.0
  tsx: ^4.17.0
  typescript: ^5.6.2
  vitest: ^4.0.3
  '@vitest/coverage-v8': ^4.0.3
  better-auth: 1.3.32
  tsdown: ^0.13.4
  '@corentinth/chisels': 2.1.0

ignoredBuiltDependencies:
  - esbuild
  - tesseract.js

onlyBuiltDependencies:
  - canvas
  - core-js
  - sharp
