# fly.toml app configuration file generated for papra-server on 2025-10-18T12:55:23Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'papra-server'
primary_region = 'cdg'

[build]
dockerfile = "./Dockerfile"

[http_service]
internal_port = 1221
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = [ 'app' ]
