blank_issues_enabled: true
contact_links:
  - name: 💬 Discord Community
    url: https://papra.app/discord
    about: Join the Papra Discord community to get help, share your feedback, and stay updated on the project.
