import { CUSTOM_PROPERTY_TYPES } from '../custom-properties/custom-properties.constants';

export const MAX_EXTRACTED_FILENAME_LENGTH = 255;

export const EXTRACTABLE_CUSTOM_PROPERTY_TYPES = [
  CUSTOM_PROPERTY_TYPES.TEXT,
  CUSTOM_PROPERTY_TYPES.NUMBER,
  CUSTOM_PROPERTY_TYPES.DATE,
  CUSTOM_PROPERTY_TYPES.BOOLEAN,
  CUSTOM_PROPERTY_TYPES.SELECT,
  CUSTOM_PROPERTY_TYPES.MULTI_SELECT,
] as const;

export type ExtractableCustomPropertyType = (typeof EXTRACTABLE_CUSTOM_PROPERTY_TYPES)[number];
