name: Release new versions

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read
  packages: write

jobs:
  docker-release:
    name: Release Docker images
    runs-on: ubuntu-latest
    steps:
      - name: Get release version from tag
        if: ${{ github.event_name == 'push' }}
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
    
      - name: Get release version from input
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: echo "RELEASE_VERSION=${{ github.event.inputs.release_version }}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push root Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            corentinth/papra:latest-root
            corentinth/papra:${{ env.RELEASE_VERSION }}-root
            ghcr.io/corentinth/papra:latest-root
            ghcr.io/corentinth/papra:${{ env.RELEASE_VERSION }}-root

      - name: Build and push rootless Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile.rootless
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            corentinth/papra:latest-rootless
            corentinth/papra:${{ env.RELEASE_VERSION }}-rootless
            ghcr.io/corentinth/papra:latest-rootless
            ghcr.io/corentinth/papra:${{ env.RELEASE_VERSION }}-rootless